package simple

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	cloud_api_client "github.com/aptible/cloud-api-clients/clients/go"
)

// TODO - autogenerated
type SimpleAssetParameters struct {
	Name types.String `tfsdk:"name" json:"name"`
}

// TODO - autogenerated
type Simple struct {
	// TOP LEVEL keys
	Id             types.String `tfsdk:"id" json:"id"`
	AssetPlatform  types.String `tfsdk:"asset_platform" json:"asset_platform"`
	AssetType      types.String `tfsdk:"asset_type" json:"asset_type"`
	AssetVersion   types.String `tfsdk:"asset_version" json:"asset_version"`
	EnvironmentId  types.String `tfsdk:"environment_id" json:"environment_id"`
	OrganizationId types.String `tfsdk:"organization_id" json:"organization_id"`
	Status         types.String `tfsdk:"status" json:"status"`

	// ASSET PARAMETER fields
	Name types.String `tfsdk:"name" json:"name"`
	// Description
	// Tags map string/string
}

// TODO - autogenerated (hence common fields, don't be alarmed at that)
// TODO - freeze below maps with immutable or freeze libraries
var AssetSchema = map[string]tfsdk.Attribute{
	"id": {
		Description: "A valid asset id",
		Type:        types.StringType,
		Computed:    true,
	},
	"environment_id": {
		Description: "A valid environment id",
		Type:        types.StringType,
		Required:    true,
	},
	"organization_id": {
		Description: "A valid organization id",
		Type:        types.StringType,
		Required:    true,
	},
	"asset_platform": {
		Type:     types.StringType,
		Required: true,
	},
	"asset_type": {
		Type:     types.StringType,
		Required: true,
	},
	"asset_version": {
		Type:     types.StringType,
		Required: true,
	},
	"name": {
		Type:     types.StringType,
		Required: true,
	},
	"status": {
		Type:     types.StringType,
		Computed: true,
		Optional: true,
	},
}

func GenerateResourceFromAssetOutput(output *cloud_api_client.AssetOutput) (*Simple, error) {
	var assetParameters SimpleAssetParameters
	rawData, err := json.Marshal(output.CurrentAssetParameters.Data)
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(rawData, &assetParameters); err != nil {
		return nil, err
	}

	return &Simple{
		Id:             types.String{Value: output.Id},
		AssetPlatform:  types.String{Value: "null"},
		AssetType:      types.String{Value: "simple"},
		AssetVersion:   types.String{Value: output.AssetVersion},
		EnvironmentId:  types.String{Value: output.Environment.Id},
		OrganizationId: types.String{Value: output.Environment.Organization.Id},
		Status:         types.String{Value: string(output.Status)},
		Name:           types.String{Value: assetParameters.Name.Value},
	}, nil
}
