package simple

import (
	"encoding/json"
	cloud_api_client "github.com/aptible/cloud-api-clients/clients/go"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aptible/terraform-provider-aptible-iaas/internal/provider/common"
)

// TODO - autogenerated
type SimpleAssetParameters struct {
	Name types.String `tfsdk:"name" json:"name"`
}

// TODO - autogenerated
type Simple struct {
	common.AssetBase
	AssetParameters SimpleAssetParameters
}

// TODO - autogenerated
// TODO - freeze below maps with immutable or freeze libraries
var AssetSchema = map[string]tfsdk.Attribute{
	"id": {
		Description: "A valid asset id",
		Type:        types.StringType,
		Computed:    true,
	},
	"environment_id": {
		Description: "A valid environment id",
		Type:        types.StringType,
		Required:    true,
	},
	"organization_id": {
		Description: "A valid organization id",
		Type:        types.StringType,
		Required:    true,
	},
	"asset_platform": {
		Type:     types.StringType,
		Required: true,
	},
	"asset_type": {
		Type:     types.StringType,
		Required: true,
	},
	"asset_version": {
		Type:     types.StringType,
		Required: true,
	},
	"name": {
		Type:     types.StringType,
		Required: true,
	},
}

func GenerateResourceFromAssetOutput(output *cloud_api_client.AssetOutput) (*Simple, error) {
	var assetParameters SimpleAssetParameters
	rawData, err := json.Marshal(output.CurrentAssetParameters.Data)
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(rawData, &assetParameters); err != nil {
		return nil, err
	}

	return &Simple{
		AssetBase: common.AssetBase{
			Id:             types.String{Value: output.Id},
			AssetVersion:   types.String{Value: output.AssetVersion},
			EnvironmentId:  types.String{Value: output.Environment.Id},
			OrganizationId: types.String{Value: output.Environment.Organization.Id},
			Status:         types.String{Value: string(output.Status)},
		},
		AssetParameters: assetParameters,
	}, nil
}
