name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ^1.0.0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      # TODO - uncomment below block when tests are ready for usage
      # - run: go test ./...